# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 635)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.29, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 851, 571))
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(20, 20, 19);\n"
"    color: white;\n"
"    border: 0px;\n"
"    border-radius: 7px;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 181, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border: 2px solid #51B56D;\n"
"border-radius: 5px;\n"
"background-color: rgb(14, 30, 18);\n"
"color: white;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 10, 121, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border: 2px solid #51B56D;\n"
"border-radius: 5px;\n"
"background-color: rgb(14, 30, 18);\n"
"color: white;\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(900, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    font: 20pt \"Sitka\";\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(20, 20, 19);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 4, 255), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: qlineargradient(spread:pad, x1:0.761, y1:0.92, x2:0.761, y2:1, stop:0 rgba(171, 0, 3, 189), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(870, 350, 201, 41))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(20, 20, 19);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 4, 255), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: qlineargradient(spread:pad, x1:0.761, y1:0.92, x2:0.761, y2:1, stop:0 rgba(171, 0, 3, 189), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(870, 450, 201, 41))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(20, 20, 19);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 4, 255), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: qlineargradient(spread:pad, x1:0.761, y1:0.92, x2:0.761, y2:1, stop:0 rgba(171, 0, 3, 189), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(870, 550, 201, 71))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(20, 20, 19);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 4, 255), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: qlineargradient(spread:pad, x1:0.761, y1:0.92, x2:0.761, y2:1, stop:0 rgba(171, 0, 3, 189), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(870, 400, 201, 41))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(20, 20, 19);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 4, 255), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: qlineargradient(spread:pad, x1:0.761, y1:0.92, x2:0.761, y2:1, stop:0 rgba(171, 0, 3, 189), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(870, 300, 201, 41))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(20, 20, 19);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 4, 255), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: qlineargradient(spread:pad, x1:0.761, y1:0.92, x2:0.761, y2:1, stop:0 rgba(171, 0, 3, 189), stop:0.392045 rgba(2, 69, 0, 208), stop:1 rgba(50, 147, 22, 255));\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(870, 50, 191, 71))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber.setAutoFillBackground(False)
        self.lcdNumber.setStyleSheet("QLCDNumber{\n"
"border: 0px;\n"
"}")
        self.lcdNumber.setMidLineWidth(0)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Название вакансии"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Регион/город"))
        self.label.setText(_translate("MainWindow", "Найдено"))
        self.pushButton_2.setText(_translate("MainWindow", "Поиск"))
        self.pushButton_3.setText(_translate("MainWindow", "График З/П"))
        self.pushButton_4.setText(_translate("MainWindow", "Облако навыков"))
        self.pushButton_6.setText(_translate("MainWindow", "Сохранить в xlsx"))
        self.pushButton_5.setText(_translate("MainWindow", "График З/П по регионам"))
        self.pushButton_7.setText(_translate("MainWindow", "Диаграмма регионов"))
