# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1079, 630)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color: #060212;\n"
"color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 851, 571))
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"    background-color: #060212;\n"
"    color: white;\n"
"    border: 0px;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 181, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border: 2px solid #5e6aa6;\n"
"border-radius: 5px;\n"
"background-color: #46405e;\n"
"color: white;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 10, 121, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border: 2px solid #5e6aa6;\n"
"border-radius: 5px;\n"
"background-color: #46405e;\n"
"color: white;\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(860, 50, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"border: 2px solid #060212;\n"
"background-color: #060212;\n"
"color: #1c7038;\n"
"}")
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(870, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"color: #1c7038\n"
"}")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 10, 141, 31))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(209,209,217);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  background: linear-gradient(rgb(110,11,12), rgb(81,8,8)) rgb(110,11,12);\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: linear-gradient(rgb(126,12,13), rgb(70,7,7)) rgb(126,12,13);\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: linear-gradient(rgb(76,7,8), rgb(56,5,6)) rgb(76,7,8);\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(870, 430, 201, 31))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(209,209,217);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  background: linear-gradient(rgb(110,11,12), rgb(81,8,8)) rgb(110,11,12);\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: linear-gradient(rgb(126,12,13), rgb(70,7,7)) rgb(126,12,13);\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: linear-gradient(rgb(76,7,8), rgb(56,5,6)) rgb(76,7,8);\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(870, 510, 201, 31))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(209,209,217);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  background: linear-gradient(rgb(110,11,12), rgb(81,8,8)) rgb(110,11,12);\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: linear-gradient(rgb(126,12,13), rgb(70,7,7)) rgb(126,12,13);\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: linear-gradient(rgb(76,7,8), rgb(56,5,6)) rgb(76,7,8);\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(870, 550, 201, 71))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(209,209,217);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  background: linear-gradient(rgb(110,11,12), rgb(81,8,8)) rgb(110,11,12);\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: linear-gradient(rgb(126,12,13), rgb(70,7,7)) rgb(126,12,13);\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: linear-gradient(rgb(76,7,8), rgb(56,5,6)) rgb(76,7,8);\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(940, 130, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"color: white;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(930, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setStyleSheet("QPlainTextEdit{\n"
"border: 2px solid #060212;\n"
"background-color: #060212;\n"
"color: white;\n"
"}")
        self.plainTextEdit_3.setPlainText("")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(870, 160, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"color: white;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(870, 220, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"color: white\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(870, 190, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"color: white;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(930, 190, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setStyleSheet("QPlainTextEdit{\n"
"border: 2px solid #060212;\n"
"background-color: #060212;\n"
"color: white;\n"
"}")
        self.plainTextEdit_4.setPlainText("")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(930, 220, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.plainTextEdit_5.setFont(font)
        self.plainTextEdit_5.setStyleSheet("QPlainTextEdit{\n"
"border: 2px solid #060212;\n"
"background-color: #060212;\n"
"color: white;\n"
"}")
        self.plainTextEdit_5.setPlainText("")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(870, 470, 201, 31))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(209,209,217);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  background: linear-gradient(rgb(110,11,12), rgb(81,8,8)) rgb(110,11,12);\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: linear-gradient(rgb(126,12,13), rgb(70,7,7)) rgb(126,12,13);\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: linear-gradient(rgb(76,7,8), rgb(56,5,6)) rgb(76,7,8);\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(870, 390, 201, 31))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"   position: relative;\n"
"  display: inline-block;\n"
"  font-size: 90%;\n"
"  font-weight: 700;\n"
"  color: rgb(209,209,217);\n"
"  text-decoration: none;\n"
"  text-shadow: 0 -1px 2px rgba(0,0,0,.2);\n"
"  padding: .5em 1em;\n"
"  outline: none;\n"
"  border-radius: 10px;\n"
"  background: linear-gradient(rgb(110,11,12), rgb(81,8,8)) rgb(110,11,12);\n"
"  box-shadow:\n"
"   0 1px rgba(255,255,255,.2) inset,\n"
"   0 3px 5px rgba(0,1,6,.5),\n"
"   0 0 1px 1px rgba(0,1,6,.2);\n"
"  transition: .2s ease-in-out;\n"
"} \n"
"\n"
"QPushButton:hover{\n"
" background: linear-gradient(rgb(126,12,13), rgb(70,7,7)) rgb(126,12,13);\n"
" }\n"
"\n"
"QPushButton:pressed{\n"
" top: 1px;\n"
"  background: linear-gradient(rgb(76,7,8), rgb(56,5,6)) rgb(76,7,8);\n"
"  box-shadow:\n"
"   0 0 1px rgba(0,0,0,.5) inset,\n"
"   0 2px 3px rgba(0,0,0,.5) inset,\n"
"   0 1px 1px rgba(255,255,255,.1);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Название вакансии"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Регион/город"))
        self.label.setText(_translate("MainWindow", "Найдено:"))
        self.pushButton_2.setText(_translate("MainWindow", "Поиск"))
        self.pushButton_3.setText(_translate("MainWindow", "График З/П"))
        self.pushButton_4.setText(_translate("MainWindow", "Облако навыков"))
        self.pushButton_6.setText(_translate("MainWindow", "Сохранить в xlsx"))
        self.label_3.setText(_translate("MainWindow", "З/П"))
        self.label_4.setText(_translate("MainWindow", "МИН:"))
        self.label_5.setText(_translate("MainWindow", "МАКС: "))
        self.label_6.setText(_translate("MainWindow", "СРЕДН: "))
        self.pushButton_5.setText(_translate("MainWindow", "График З/П по регионам"))
        self.pushButton_7.setText(_translate("MainWindow", "Диаграмма регионов"))
